// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrn3Idi-qYbhKbwWdwWrIeqX7YYk8JPWU',
    appId: '1:363230035601:web:33064d4e1790774fa34930',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    authDomain: 'ness-alkheirapp.firebaseapp.com',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewraw4FIKKGNWMloB8_Nhhay0stlejV0',
    appId: '1:363230035601:android:ddc73f9642880a66a34930',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrJV0WgtNXmAxAPLrrcbSPXOxeZntjYM',
    appId: '1:363230035601:ios:73438a1129bfbcbfa34930',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
    androidClientId: '363230035601-6nc6rer9b9ofhq94107ssiqhpkd917ce.apps.googleusercontent.com',
    iosClientId: '363230035601-aa866ud4mldc3l3hj1msu8nmsbcd2mbi.apps.googleusercontent.com',
    iosBundleId: 'com.nasalkheir.nasAlKheir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrJV0WgtNXmAxAPLrrcbSPXOxeZntjYM',
    appId: '1:363230035601:ios:73438a1129bfbcbfa34930',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
    androidClientId: '363230035601-6nc6rer9b9ofhq94107ssiqhpkd917ce.apps.googleusercontent.com',
    iosClientId: '363230035601-aa866ud4mldc3l3hj1msu8nmsbcd2mbi.apps.googleusercontent.com',
    iosBundleId: 'com.nasalkheir.nasAlKheir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrn3Idi-qYbhKbwWdwWrIeqX7YYk8JPWU',
    appId: '1:363230035601:web:1eb275be6c5f7102a34930',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    authDomain: 'ness-alkheirapp.firebaseapp.com',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
  );

}
