// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGcs0B5Od2jceKoB7IhJP4HW5geW0ric',
    appId: '1:197382034070:web:7f45daf168efe78d5768b7',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    authDomain: 'ness-alkheirapp.firebaseapp.com',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewraw4FIKKGNWMloB8_Nhhay0stlejV0',
    appId: '1:363230035601:android:ddc73f9642880a66a34930',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpilmU6N16VomvrccinUe6V-wFKTe84k',
    appId: '1:197382034070:ios:0f53add86a41b0fa5768b7',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
    iosBundleId: 'com.nasalkheir.nasAlKheir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpilmU6N16VomvrccinUe6V-wFKTe84k',
    appId: '1:197382034070:ios:0f53add86a41b0fa5768b7',
    messagingSenderId: '363230035601',
    projectId: 'ness-alkheirapp',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
    iosBundleId: 'com.nasalkheir.nasAlKheir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGcs0B5Od2jceKoB7IhJP4HW5geW0ric',
    appId: '1:197382034070:web:50241b5a7a822ea65768b7',
    messagingSenderId: '197382034070',
    projectId: 'ness-alkheirapp',
    authDomain: 'ness-alkheirapp.firebaseapp.com',
    storageBucket: 'ness-alkheirapp.firebasestorage.app',
  );
}

